//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderedProblems
    {
        public int Id { get; set; }
        public int Order { get; set; }
        public int ProblemId { get; set; }
        public int ProblemSetId { get; set; }
    
        public virtual Problems Problem { get; set; }
        public virtual ProblemSets ProblemSet { get; set; }
    }
}
